name: Deploy to Tencent COS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Build project
        run: npm i -g pnpm && pnpm install && pnpm build

      - name: Build
        run: pnpm build

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install coscmd
        run: pip install coscmd

      - name: Configure coscmd
        run: |
          coscmd config \
            -a ${{ secrets.SECRET_ID }} \
            -s ${{ secrets.SECRET_KEY }} \
            -b ${{ secrets.BUCKET }} \
            -r ap-shanghai

      - name: Upload to COS
        run: coscmd upload -rfs --delete dist/ /
